version: '2.1'
networks: {}
volumes:
  node-red-eq3-data: {}
services:
  node-red-eq3:
    build: node-red-eq3
    privileged: true
    restart: always
    network_mode: host
    ports:
       - "80:1880"
    volumes:
      - 'node-red-eq3-data:/data'
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
      io.balena.update.strategy: download-then-kill
      io.balena.update.handover-timeout: ''
